{% set name = "types-s3transfer" %}
{% set version = "0.6.1" %}
{% set lib_version = version.split(".post")[0] %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 75ac1d7143d58c1e6af467cfd4a96c67ee058a3adf7c249d9309999e1f5f41e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.7,<4.0
    - pip

test:
  requires:
    - pip
    - poetry
  commands:
    - pip check
    - python -c "import importlib; importlib.import_module('s3transfer-stubs')"

about:
  home: https://github.com/youtype/types-s3transfer
  summary: Type annotations for AWS s3transfer {{ lib_version }} library
  dev_url: https://github.com/youtype/types-s3transfer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vemel
