schema_version: 1

context:
  name: types-s3transfer
  version: 0.10.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_s3transfer-${{ version }}.tar.gz
  sha256: 60167a3bfb5c536ec6cdb5818f7f9a28edca9dc3e0b5ff85ae374526fc5e576e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - types-awscrt

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
  - package_contents:
      site_packages:
        - s3transfer-stubs/__init__.pyi

about:
  summary: Type annotations for AWS s3transfer
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/youtype/types-s3transfer
  repository: https://github.com/youtype/types-s3transfer

extra:
  recipe-maintainers:
    - vemel
    - xhochy
